const mongoose = require('mongoose');

const UserPromptSchema = new mongoose.Schema({
    promptText: {
        type: String,
        required: [true, 'Please add a prompt text'],
        trim: true,
        maxlength: [500, 'Prompt can not be more than 500 characters']
    },
    interviewGoal: {
        type: String, // Generated by AI
        default: ''
    },
    intentMap: {
        type: [String], // Array of planned question topics/intents
        default: []
    },
    createdAt: {
        type: Date,
        default: Date.now
    }
});

module.exports = mongoose.model('UserPrompt', UserPromptSchema);
